##############
## Services ##
##############

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
      - ../secrets
    restart: on-failure

  ### BONUS PART ###

  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    restart: on-failure
    expose:
      - 6379
  
  adminer:
    container_name: adminer
    env_file:
      - .env
      - ../secrets
    depends_on:
      - mariadb
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    expose:
      - 9000

  ftp:
    container_name: ftp
    env_file:
      - .env
      - ../secrets
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    ports:
      - "20:20"
      - "21:21"
  
  pong:
    container_name: pong
    build:
      context: requirements/bonus/pong
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    ports:
      - "8080:8080"
  
  squid:
    container_name: squid
    build:
      context: requirements/bonus/squid
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8888:8888"


#############
## Volumes ##
#############

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress


##############
## Networks ##
##############

networks:
  inception:
    driver: bridge
